mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static 
from shop import views

urlpatterns =[
    path('' , include("shop.urls")),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name="shop"

urlpatterns = [
    path("", views.index, name="home" ),
    path("product/<str:product_name>/", views.product_detail, name="product_detail" ),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('stores/', TemplateView.as_view(template_name='stores.html'), name='stores'),
    path('terms/', TemplateView.as_view(template_name='terms.html'), name='terms'),
    path('privacy-policy/', TemplateView.as_view(template_name='privacy.html'), name='privacy'),
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.exceptions import ValidationError

class ProductCat(models.Model):
    PRODUCT_TYPE_CHOICES=[
        ('Whey Protein', 'Whey Protein'),
        ('Mass Gainer', 'Mass Gainer'),
        ('Pre Workout', 'Pre Workout'),
        ('Peanut Butter', 'Peanut Butter'),
        ('Protein Bar', 'Protein Bar'),
    ]
    
    name = models.CharField(max_length=255)
    brand = models.CharField(max_length=255)
    product_type = models.CharField(
        max_length=100,
        choices=PRODUCT_TYPE_CHOICES,
        )
    
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    productcat = models.ForeignKey(ProductCat, on_delete=models.CASCADE, related_name="productcat")
    sku = models.CharField(max_length=100, unique=True)
    flavour = models.CharField(max_length=255)  # e.g., "Chocolate", "Honey"
    size = models.PositiveIntegerField()
    SIZE_UNIT_CHOICES = [
        ('kg', 'Kilogram'),
        ('gm', 'Gram'),
    ]
    size_unit = models.CharField(
        max_length=2, 
        choices=SIZE_UNIT_CHOICES, 
        default='kg'  # Default to kg
        )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    front_image = models.ImageField(upload_to='front_images/')
    is_discounted = models.BooleanField(default=False)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # Discounted price (can be null)
    bestselling_rank = models.PositiveIntegerField()
    stock = models.PositiveIntegerField()  # Stock count
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_discount_percentage(self):
        if self.discounted_price and self.price:
            return int(round(((self.price - self.discounted_price) / self.price) * 100, 2))
        return 0
    def __str__(self):
        return f"{self.sku}"


class ProductImage(models.Model):
# Image related to the product
    sku = models.ForeignKey(Product,on_delete=models.CASCADE,to_field="sku",related_name="images")
    image = models.ImageField(upload_to='product_images/')
    is_primary = models.BooleanField(default=False)
    alt_text = models.CharField(max_length=255, blank=True, null=True)  # Optional alt text
    image_order = models.PositiveIntegerField(default=0)  # Optional field for ordering images
    
    def __str__(self):
        return f"Image -{self.image_order}- {self.sku} - {self.alt_text}"
@receiver(post_delete, sender=ProductImage)
def delete_image_file(sender, instance, **kwargs):
    if instance.image:
        image_path = instance.image.path
        if os.path.isfile(image_path):
            os.remove(image_path)

class HomepageBanner(models.Model):
    title = models.CharField(max_length=100)  # For identifying the image
    image = models.ImageField(upload_to='homepage_banners/')  # Folder for these images
    # link_url = models.URLField(blank=True, null=True)  # Optional link for redirection
    is_active = models.BooleanField(default=True)  # To toggle visibility
    display_order = models.PositiveIntegerField(default=0)  # For ordering banners
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['display_order']  # Default ordering

    def __str__(self):
        return self.title

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from datetime import datetime,timedelta
from .models import ProductCat,Product,ProductImage,HomepageBanner
from django.http import HttpResponse

# Create your views here.
def index(request):
    banners=HomepageBanner.objects.all()
    best=Product.objects.order_by('bestselling_rank')[:4]
    return render(request, 'homepage.html',{
        'banners':banners,
        'best':best,
    })
def product_detail(request,product_name):
    product = get_object_or_404(Product, sku=product_name)
    print(product)
    images = ProductImage.objects.filter(sku=product)
    return render(request, 'product.html',{'product':product,'images':images})

shop/templates/about.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="sm:flex items-center max-w-screen-xl">
    <div class="sm:w-1/2 p-10">
        <div class="image object-center text-center">
            <img src="https://i.imgur.com/WbQnbas.png">
        </div>
    </div>
    <div class="sm:w-1/2 px-5 pb-10 sm:border-y-0 border-b-8">
        <div class="text">
            <h2 class="my-8 font-bold text-3xl text-center sm:text-4xl ">About <span class="">Our Company</span>
            </h2>
            <p class="text-gray-700 text-center">
                CoreCrust is a revolutionary health supplement brand dedicated to providing high
                quality, performance-driven nutrition for fitness enthusiasts, athletes, and health
                conscious individuals. With a core focus on whey protein, peanut butter, and other 
                high-performance supplements, CoreCrust is built on the pillars of purity, science, and 
                innovation. We believe that true fitness starts from within, and our mission is to fuel 
                every journey with clean, effective, and delicious nutrition that enhances strength, 
                endurance, and overall well-being.
            </p>
            <h2 class="my-8 font-bold text-3xl text-center sm:text-4xl ">Vision
            </h2>
            <p class="text-gray-700 text-center">
                Our vision is to become a trusted name in the fitness industry by prioritizing 
                transparency, premium ingredients, and rigorous quality standards. At CoreCrust, we 
                don’t just sell supplements—we create a movement centered around health, discipline, 
                and progress. Whether you're an elite athlete or someone taking the first step towards 
                a healthier lifestyle, our products are designed to support you at every stage. We are 
                committed to continuous research, innovation, and community building, ensuring that 
                CoreCrust becomes the go-to brand for those who refuse to compromise on quality and 
                performance.
            </p>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/contact.html
{% comment %} {% extends "index.html" %}
{% load static %}
{% block content %}
<div id="contact-us" class="overflow-hidden bg-white py-16 px-4 dark:bg-slate-900 sm:px-6 lg:px-8 lg:py-24">
    <div class="relative mx-auto max-w-xl">
        <svg class="absolute left-full translate-x-1/2 transform" width="404" height="404" fill="none"
            viewBox="0 0 404 404" aria-hidden="true">
            <defs>
                <pattern id="85737c0e-0916-41d7-917f-596dc7edfa27" x="0" y="0" width="20" height="20"
                    patternUnits="userSpaceOnUse">
                    <rect x="0" y="0" width="4" height="4" class="text-gray-200 dark:text-slate-600"
                        fill="currentColor"></rect>
                </pattern>
            </defs>
            <rect width="404" height="404" fill="url(#85737c0e-0916-41d7-917f-596dc7edfa27)"></rect>
        </svg>
        <svg class="absolute right-full bottom-0 -translate-x-1/2 transform" width="404" height="404" fill="none"
            viewBox="0 0 404 404" aria-hidden="true">
            <defs>
                <pattern id="85737c0e-0916-41d7-917f-596dc7edfa27" x="0" y="0" width="20" height="20"
                    patternUnits="userSpaceOnUse">
                    <rect x="0" y="0" width="4" height="4" class="text-gray-200 dark:text-slate-800"
                        fill="currentColor"></rect>
                </pattern>
            </defs>
            <rect width="404" height="404" fill="url(#85737c0e-0916-41d7-917f-596dc7edfa27)"></rect>
        </svg>
        <div class="text-center">
            <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-slate-200 sm:text-4xl">Contact Us
            </h2>
            <p class="mt-4 text-lg leading-6 text-gray-500 dark:text-slate-400">Please use the form below to contact us.
                Thank you!
            </p>
        </div>
        <div class="mt-12">
            <form class="grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">
                <div class="sm:col-span-2">
                    <label for="name" class="block text-sm font-medium text-gray-700 dark:text-slate-400">Name</label>
                    <div class="mt-1">
                        <input name="name" type="text" id="name" autocomplete="organization" required="" class="border border-gray-300 block w-full rounded-md py-3 px-4 shadow-sm focus:border-sky-500 focus:ring-sky-500 dark:border-white/5 dark:bg-slate-700/50 dark:text-white">
                    </div>
                </div>
                <div class="sm:col-span-2">
                    <label for="email" class="block text-sm font-medium text-gray-700 dark:text-slate-400">Email</label>
                    <div class="mt-1">
                        <input name="email" id="email" required="" type="email" autocomplete="email" class="border border-gray-300 block w-full rounded-md py-3 px-4 shadow-sm focus:border-sky-500 focus:ring-sky-500 dark:border-white/5 dark:bg-slate-700/50 dark:text-white">
                    </div>
                </div>
                <div class="sm:col-span-2">
                    <label for="message" class="block text-sm font-medium text-gray-700 dark:text-slate-400">Message</label>
                    <div class="mt-1">
                        <textarea required="" name="message" id="message" rows="4" class="border border-gray-300 block w-full rounded-md py-3 px-4 shadow-sm focus:border-sky-500 focus:ring-sky-500 dark:border-white/5 dark:bg-slate-700/50 dark:text-white"></textarea>
                    </div>
                </div>
                <div class="flex justify-end sm:col-span-2">
                    <button type="submit" class="inline-flex items-center rounded-md px-4 py-2 font-medium focus:outline-none focus-visible:ring focus-visible:ring-sky-500 shadow-sm sm:text-sm transition-colors duration-75 text-sky-500 border border-sky-500 hover:bg-sky-50 active:bg-sky-100 disabled:bg-sky-100 dark:hover:bg-gray-900 dark:active:bg-gray-800 dark:disabled:bg-gray-800 disabled:cursor-not-allowed">
                        <span>Send Message</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} {% endcomment %}

shop/templates/homepage.html
{% extends "index.html" %}

{% block content %}
<div class="relative">
    <div class="carousel w-full">
        {% for banner in banners %}
        <div class="carousel-item w-full">
            <img src="{{ banner.image.url }}" alt="{{ banner.alt_text }}" class="w-full object-cover">
        </div>
        {% endfor %}
    </div>
    <!-- Navigation for carousel -->
    <div class="absolute inset-x-0 bottom-0 flex justify-center space-x-4">
        {% for banner in banners %}
        <button class="w-3 h-3 rounded-full bg-gray-300 hover:bg-gray-600"></button>
        {% endfor %}
    </div>
</div>

<div class="bg-orange-100">
    <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900">Our Bestsellers</h2>
  
      <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
        {% for product in best %}
        <div class="group relative">
          <a href="{% url 'shop:product_detail' product.sku %}">
          <img src="{{product.front_image.url}}" alt="" class="aspect-square w-full rounded-md bg-gray-200 object-cover group-hover:opacity-75 lg:aspect-auto lg:h-80">
          </a>
          <div class="mt-4  flex justify-center">
            <div>
              <h3 class="text-sm text-gray-700">
                <a href="{% url 'shop:product_detail' product.sku %}" class="font-semibold">
                  <span aria-hidden="true" class="absolute inset-0"></span>
                  {{product.productcat}}
                </a>
              </h3>
              {% comment %} <p class="mt-1 text-sm text-gray-500">{{product.flavour}}</p> {% endcomment %}
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- More products... -->
      </div>
    </div>
  </div>
  
{% endblock %}

shop/templates/privacy.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="bg-gray-100">
    <div class="container mx-auto px-4 py-8">
        <h1 class="text-3xl font-bold mb-4">Terms of Service</h1>

        <p class="mb-4">
            This privacy policy sets out how our website uses and protects any information that you give us when you use
            this
            website.
        </p>

        <h2 class="text-2xl font-bold mb-2">Information We Collect</h2>

        <p class="mb-4">
            We may collect the following information:
        </p>

        <ul class="list-disc list-inside mb-4">
            <li>Your name and contact information</li>
            <li>Demographic information</li>
            <li>Other information relevant to customer surveys and/or offers</li>
        </ul>

        <h2 class="text-2xl font-bold mb-2">How We Use the Information</h2>

        <p class="mb-4">
            We require this information to understand your needs and provide you with a better service, and in
            particular
            for
            the following reasons:
        </p>

        <ul class="list-disc list-inside mb-4">
            <li>Internal record keeping</li>
            <li>Improving our products and services</li>
            <li>Sending promotional emails about new products, special offers, or other information which we think you
                may
                find
                interesting</li>
            <li>From time to time, we may also use your information to contact you for market research purposes. We may
                contact
                you by email, phone, or mail. We may use the information to customize the website according to your
                interests.</li>
        </ul>

        <h2 class="text-2xl font-bold mb-2">Security</h2>

        <p class="mb-4">
            We are committed to ensuring that your information is secure. In order to prevent unauthorized access or
            disclosure,
            we have put in place suitable physical, electronic, and managerial procedures to safeguard and secure the
            information we collect online.
        </p>

        <h2 class="text-2xl font-bold mb-2">Cookies</h2>

        <p class="mb-4">
            A cookie is a small file that asks permission to be placed on your computer's hard drive. Once you agree,
            the
            file
            is added, and the cookie helps analyze web traffic or lets you know when you visit a particular site.
            Cookies
            allow
            web applications to respond to you as an individual. The web application can tailor its operations to your
            needs,
            likes, and dislikes by gathering and remembering information about your preferences.
        </p>

        <p class="mb-4">
            Overall, cookies help us provide you with a better website by enabling us to monitor which pages you find
            useful
            and which you do not. A cookie in no way gives us access to your computer or any information about you,
            other
            than
            the data you choose to share with us.
        </p>

        <h2 class="text-2xl font-bold mb-2">Links to Other Websites</h2>

        <p class="mb-4">
            Our website may contain links to other websites of interest. However, once you have used these links to
            leave
            our
            site, you should note that we do not have any control over that other website. Therefore, we cannot be
            responsible
            for the protection and privacy of any information which you provide whilst visiting such sites and such
            sites
            are
            not governed by this privacy statement. You should exercise caution and look at the privacy statement
            applicable
            to
            the website in question.
        </p>

        <h2 class="text-2xl font-bold mb-2">Controlling Your Personal Information</h2>

        <p class="mb-4">
            You may choose to restrict the collection or use of your personal information in the following ways:
        </p>

        <ul class="list-disc list-inside mb-4">
            <li>If you have previously agreed to us using your personal information for direct marketing purposes, you
                may
                change your mind at any time by writing to or emailing us at [email protected]</li>
            <li>We will not sell, distribute, or lease your personal information to third parties unless we have your
                permission
                or are required by law to do so. We may use your personal information to send you promotional
                information
                about
                third parties which we think you may find interesting if you tell us that you wish this to happen.</li>
            <li>You may request details of personal information which we hold about you. If you would like a copy of the
                information held on you, please write to [Your Company Name, Address, City, State, Zip Code] or email
                [email protected]</li>
            <li>If you believe that any information we are holding on you is incorrect or incomplete, please write to or
                email
                us as soon as possible at the above address. We will promptly correct any information found to be
                incorrect.
            </li>
        </ul>

        <p class="mb-4">
            This privacy policy is subject to change without notice.
        </p>
    </div>
</div>

{% endblock %}

shop/templates/product.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<!-- Swiper.js CSS -->
<script src="{% static 'js/cart.js' %}"></script>
<h1 class="bg-white px-5 py-2 text-black text-xs">
    Home > Products > {{product.productcat}}
</h1>
<div class="md:flex items-start justify-center py-12 2xl:px-20 md:px-40 px-2">
    <div class="md:flex-1 mx-auto px-4 ">
        <!-- Product Image Section -->
        <div class="flex flex-col md:flex-row gap-10">
            <!-- Thumbnail Images (Desktop) -->
            <div class="hidden order-2 md:order-1  md:flex md:w-auto md:flex-col gap-4">
                {% for image in images %}
                <img 
                    src="{{ image.image.url }}" 
                    alt="Thumbnail {{ forloop.counter }}" 
                    class="w-full h-24 object-scale-down cursor-pointer rounded-md border border-gray-200 hover:border-blue-500"
                    onmouseover="updateMainImage('{{ image.image.url }}')">
                {% endfor %}
            </div>
    
            <!-- Main Image -->
            <div class="hidden order-1 md:order-2 md:block relative mx-auto w-5/6">
                <img 
                    id="mainImage" 
                    src="{{ images.first.image.url }}" 
                    alt="{{ product.flavour }}" 
                    class="w-fit h-auto object-contain rounded-lg shadow-md">
            </div>
    
            <!-- Slider Images (Mobile) -->
            <div class="md:hidden ">
                <div class="swiper-container z-0 flex relative overflow-hidden" >
                    <div class=" swiper-wrapper  flex relative">
                        {% for image in images %}
                        <div class="swiper-slide  ">
                            <img 
                                id="swiper"
                                src="{{ image.image.url }}" 
                                alt="Slide {{ forloop.counter }}" 
                                class="w-full h-full rounded-lg">
                        </div>
                        {% endfor %}
                    </div>  
                    <!-- Slider Navigation -->
                {% comment %} <div class="swiper-button-prev z-10"></div>
                <div class="swiper-button-next z-10"></div> {% endcomment %}
                <div class="swiper-pagination z-10"></div>                
                </div>
                
            </div>
        </div>
    </div>
    <script>
        function updateMainImage(imageUrl) {
            const mainImage = document.getElementById("mainImage");
            const swiper = document.getElementById("swiper");
            mainImage.src = imageUrl;
            swiper.src = imageUrl;
        }
        const swiper = new Swiper(".swiper-container", {
            
            loop: false, // Infinite loop for slides
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            
        });
    </script>
    <div class="md:flex-2 xl:w-2/5 md:w-1/2 lg:ml-10 px-6 md:ml-6 md:mt-0 mt-6">
        <div class="border-b border-gray-200 pb-6">
            <h1 class="text-sm leading-none font-semibold text-gray-600 dark:text-gray-300 ">Core-Crust</h1>
            <h1 class="lg:text-2xl text-xl font-semibold lg:leading-6 leading-7 text-gray-800 dark:text-white mt-2">{{product.productcat}}</h1>
        </div>
        <div class="py-4 border-b border-gray-200 flex items-center justify-between">
            <p class="text-base leading-4 text-gray-800 dark:text-gray-300">Flavour</p>
            <div class="flex items-center justify-center">
                <p class="text-sm leading-none text-gray-600 dark:text-gray-300 mr-3">{{product.flavour}}</p>
                <img class="hidden dark:block" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg2dark.svg" alt="next">   
                <img class="dark:hidden" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg2.svg" alt="next">
            </div>
        </div>
        <div class="py-4 border-b border-gray-200 flex items-center justify-between">
            <p class="text-base leading-4 text-gray-800 dark:text-gray-300">Size</p>
            <div class="flex items-center justify-center">
                <p class="text-sm leading-none text-gray-600 dark:text-gray-300 mr-3">{{product.size}} {{product.size_unit}}</p>               
                <img class="dark:hidden" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg2.svg" alt="next">
                <img class="hidden dark:block" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg2dark.svg" alt="next">  
            </div>
        </div>
        <div class="py-3 ">
            <span class="items-start text-lg text-yellow-600">
                MRP :
                <span class=" ">₹{{product.discounted_price}}</span>
                <span class="line-through text-xs text-gray-600">₹{{product.price}}</span>
            </span> 
            <span class="text-green-500 ml-2">{{product.get_discount_percentage}}% off</span>
            <p class="text-base">
                Incl. of all taxes
            </p>
        </div>
        {% if product.stock > 0 %}
        <button onclick="addToCart({{ product.id }})" id="addtocartButton" class="dark:bg-white rounded dark:text-gray-900 dark:hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 text-base flex items-center justify-center leading-none text-white bg-green-600 w-full py-4 hover:bg-green-500 ">
            Add To Cart
        </button>
        {% else%}
        <button class="dark:bg-white rounded text-base flex items-center justify-center leading-none text-white bg-gray-300 w-full py-4 ">
            Out of Stock
        </button>
        {% endif%}
        <div>
            <p class=" text-base lg:leading-tight leading-normal font-semibold text-black dark:text-gray-300 mt-7">{{product.productcat.description}}</p>
        </div>
        <div>
            <div class="border-t border-b py-4 mt-7 border-gray-200">
                <div data-menu class="flex justify-between items-center cursor-pointer">
                    <p class="text-base leading-4 text-gray-800 dark:text-gray-300">Shipping and returns</p>
                    <button class="cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400 rounded" role="button" aria-label="show or hide">
                        <img class="transform dark:hidden" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg4.svg" alt="dropdown">
                        <img class="transform hidden dark:block" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg4dark.svg" alt="dropdown">
                    </button>
                </div>
                <div class="hidden pt-4 text-base leading-normal pr-12 mt-4 text-gray-600 dark:text-gray-300" id="sect">You will be responsible for paying for your own shipping costs for returning your item. Shipping costs are nonrefundable</div>
            </div>
        </div>
        <div>
            <div class="border-b py-4 border-gray-200">
                <div data-menu class="flex justify-between items-center cursor-pointer">
                    <p class="text-base leading-4 text-gray-800 dark:text-gray-300">Contact us</p>
                    <button class="cursor-pointer focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400 rounded" role="button" aria-label="show or hide">
                        <img class="transform dark:hidden" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg4.svg" alt="dropdown">
                        <img class="transform hidden dark:block" src="https://tuk-cdn.s3.amazonaws.com/can-uploader/productDetail3-svg4dark.svg" alt="dropdown">
                    </button>
                </div>
                <div class="hidden pt-4 text-base leading-normal pr-12 mt-4 text-gray-600 dark:text-gray-300" id="sect">If you have any questions on how to return your item to us, contact us.</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/stores.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<h1 class="text-center text-4xl mt-8"> 
    Our Stores 

</h1>
<div class="max-w-6xl py-10 pb-20 border-b-8 px-5 mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <!-- Store 1 -->
    <div class="bg-white shadow-lg rounded-lg p-6 border border-gray-200">
        <h2 class="text-xl font-semibold text-gray-800">Rathee Nutrition</h2>
        <p class="text-gray-600 mt-2">Shop no 17, omaxe galleria, Sector 14, Bahadurgarh, Haryana 124507</p>
        {% comment %} <p class="text-gray-500 mt-1">📞 +123 456 7890</p> {% endcomment %}
    </div>

    <!-- Store 2 -->
    <div class="bg-white shadow-lg rounded-lg p-6 border border-gray-200">
        <h2 class="text-xl font-semibold text-gray-800">Everest Nutrition</h2>
        <p class="text-gray-600 mt-2">1st floor, Shop no 1, pingli chowk, 1, Kaithal - Karnal Rd, above krishna pharmacy, Karnal, Haryana 132001</p>
        {% comment %} <p class="text-gray-500 mt-1">📞 +987 654 3210</p> {% endcomment %}
    </div>

    <!-- Store 3 -->
    <div class="bg-white shadow-lg rounded-lg p-6 border border-gray-200">
        <h2 class="text-xl font-semibold text-gray-800">Kesri Nutrition</h2>
        <p class="text-gray-600 mt-2">598-R, 8, Chowk, Jattal Rd, Marla Colony, Model Town, Panipat, Haryana 132103</p>
        {% comment %} <p class="text-gray-500 mt-1">📞 +456 789 0123</p> {% endcomment %}
    </div>

    <div class="bg-white shadow-lg rounded-lg p-6 border border-gray-200">
        <h2 class="text-xl font-semibold text-gray-800">Rj supplements</h2>
        <p class="text-gray-600 mt-2">2X2W+X58, Gali Number 2, Shastri Colony, Sonipat, Haryana 131001</p>
        {% comment %} <p class="text-gray-500 mt-1">📞 +456 789 0123</p> {% endcomment %}
    </div>

    <!-- Add more stores here -->
</div>
{% endblock %}